variable "vpc" {}
variable "env" {}
variable "apps" {}
variable "bastion_nodes" {}
variable "db" {}
variable "vault_token" {}
variable "zone_id" {}
variable "load_balancers" {}
variable "load_balancer_type" {}
variable "subnet_ref" {}